### ISSUE TITLE
V0.0.4 log errors

### ISSUE THREAD

**Issue by dutch-erik** [PimDoos/onesmartcontrolha#1]
V0.0.4
Just FYI, because I'm sure you do see the same thing. ;)
Thanks a lot for your effort!

```
This error originated from a custom integration.

Logger: root
Source: custom_components/onesmartcontrol/onesmartwrapper.py:118
Integration: One Smart Control (documentation, issues)
First occurred: 09:14:09 (46 occurrences)
Last logged: 11:13:21

Error in gateway wrapper: 'meters'
Error in gateway wrapper: string indices must be integers
Error in gateway wrapper: list indices must be integers or slices, not dict
Error in gateway wrapper: 'devices'
Error in gateway wrapper: can't convert negative int to unsigned
Error in gateway wrapper: 'attributes'
Error in gateway wrapper: 'values'
```
```
This error originated from a custom integration.

Logger: root
Source: custom_components/onesmartcontrol/onesmartwrapper.py:115
Integration: One Smart Control (documentation, issues)
First occurred: 09:16:00 (8 occurrences)
Last logged: 11:01:03

Could not load data for COMFOAIR: {'error': 3, 'description': 'timeout'}
Could not load data for HEATPUMP: {'error': 3, 'description': 'timeout'}
Could not load data for HUAWEI SUN2000: {'error': 3, 'description': 'timeout'}
Could not load data for ONEENERGY: {'error': 300, 'description': 'Remote system error'}
Command timed out after 60 seconds: apparatus
Could not load data for HUAWEI SUN2000: {'error': 300, 'description': 'Remote system error'}```

**Comment by PimDoos** [comment]
Thanks for the report! Despite the errors, do your sensors show up in HA?
I do expect some timeouts occasionally, as the modbus operations to the inverter, wtw and heatpump are not very reliable. I might suppress these later, as they (mostly) don't really affect operations as long as not _all_ commands are timing out.

The errors in the top snippet should be fixed in v0.0.5.

**Comment by PimDoos** [comment]
Fixed in [v0.0.5](https://github.com/PimDoos/onesmartcontrolha/releases/tag/v0.0.5)

**Comment by dutch-erik** [comment]
Yes, 4 devices and 70 entities do show up.
Sun2000: I'm missing some entities, for example: yield total day, yield total. I see them in the One portal.

**Comment by PimDoos** [comment]
Energy sensors for Sun2000 will be added later, they are available as appartus attributes 'e_total' and 'e_day'. I'm also planning to add more sensors for the heatpump and add climate entities for Sun2000 and the heat pump.
