### ISSUE TITLE
Heatpump climate change temperature not working

### ISSUE THREAD

**Issue by mirkin-pixel** [PimDoos/onesmartcontrolha#41]
When I change the temperature via the climate.heatpump, it does not change in the end and it remains at the read value.

**Comment by PimDoos** [comment]
This is a known issue, and seems to be caused by the OneEnergy not forwarding our write commands to the heatpump. I'll see if I can reach someone at OSC about this.

**Comment by PimDoos** [comment]
Sorry for letting this go stale, I haven't taken the time to contact One Smart Control yet.
I expect to have some time to take care of this in january.

**Comment by mirkin-pixel** [comment]
No problem, it's not in a hurry, it's just a nice addition if it does work

**Comment by mirkin-pixel** [comment]
@PimDoos have you had time to look at this yet? Is there also a possibility that the wtw can be operated or is this impossible?

**Comment by PimDoos** [comment]
I just reached out to them, I'll let you know how it goes.

**Comment by PimDoos** [comment]
Update: OneSmartControl initially responded very positively and assured they would get back to me, but unfortunately I have not seen a response in a while.
