### ISSUE TITLE
Can digits behind Rpm be rounded to 0?

### ISSUE THREAD

**Issue by dutch-erik** [PimDoos/onesmartcontrolha#42]
Hi Pim,

COMFOAIR Inlet Ventilator Rpm -> 1.238,44121532365 rpm
COMFOAIR Outlet Ventilator Rpm -> 1.033,62734288864 rpm

Many digits behind the comma, can this be rounded to 0?

**Comment by PimDoos** [comment]
Home Assistant 2023.2 introduces a feature to change precision of an entity. This should make this significantly (pun not intended) easier to implement, so I'll have a look at it when I have the time

**Comment by PimDoos** [comment]
Fixed in HA 2023.3 and OneSmartControlHA 0.3.4:

You can change the desired precision in the entity settings menu.
![image](https://user-images.githubusercontent.com/17709721/222277733-a25be01c-590e-45b1-be59-b39dc3f89daf.png)

**Comment by PimDoos** [comment]
See also https://www.home-assistant.io/blog/2023/03/01/release-20233/#sensor-display-precision
