### ISSUE TITLE
Instellen mislukt: None

### ISSUE THREAD

**Issue by Jeffie79** [PimDoos/onesmartcontrolha#45]
I’m not able to get access.
Can I just use the portal login?
I got the Ip adress from my router, zo that should be right.
When using the portal login, it looks good.
But the intergration is not ik!
![700D4934-EC86-4EBE-ACAB-0AF24A71FC1B](https://user-images.githubusercontent.com/77285769/212487726-362c223e-54cb-4a78-bd97-0ce459f8d6d9.jpeg)

**Comment by PimDoos** [comment]
The integration uses the local socket used by the OneSmartControl app. You should use the same credentials you used in the app.
If it does work in the app, is there anything in the Home Assistant logs for this integration?

**Comment by PimDoos** [comment]
My house was also built by MorgenWonen. I used the normal setup wizard in the app to create a user and login. I do remember it took a few tries before I could actually login, the setup wizard was a bit glitchy.

**Comment by djmaupp** [comment]
I have the same. I have access to the portal. But when I open the app it says no connection possible make sure you have a working server in you’re home. But I have it and can see it in the network. 

Does resetting it block it from morgenwonen?

**Comment by Jeffie79** [comment]
The best thing you can do, is to make contact with OneSmartControle and tell them your problem.
It is possible for them to look in to de server in your home and see what the login should be.
When you have the correct login then the rest is easy.

**Comment by djmaupp** [comment]
When I plugged it back into my network. The app suddenly gave me the chance to register. So I did that and now I can use the app and home assistant. Hopefully the service provider can also see the data because it’s a rental house 😅

**Comment by PimDoos** [comment]
Closing as the issue seems to be resolved. Fix seems to be to restart the unit or let it reconnect to ethernet.
