### ISSUE TITLE
Loggin in

### ISSUE THREAD

**Issue by bastiaanvanraaij** [PimDoos/onesmartcontrolha#52]
Sorry for this noob question, i'm alread happy that i'm this far... What should be the host for loggin in. Username and password should be from digitalstrom account or from the actual ds configurator??

**Comment by PimDoos** [comment]
I'm not sure if this integration also works for DigitalStrom. For One Smart Control, the host is the IP address of the central One Connect unit on your local network (likely starts with 192.168.). The username and password are the credentials you use to login to the One Smart Control app.
