### ISSUE TITLE
Error while discovering entities for device HEATPUMP: LITER

### ISSUE THREAD

**Issue by dutch-erik** [PimDoos/onesmartcontrolha#64]
Latest version: 0.4.2 - error below:

-----------------------
This error originated from a custom integration.

Logger: custom_components.onesmartcontrol.onesmartwrapper
Source: custom_components/onesmartcontrol/onesmartwrapper.py:732
Integration: One Smart Control (documentation, issues)
First occurred: 20:19:06 (1 occurrences)
Last logged: 20:19:06

Error while discovering entities for device HEATPUMP: LITER

-----------------------

**Comment by PimDoos** [comment]
Fixed in release [v0.4.3](https://github.com/PimDoos/onesmartcontrolha/releases/tag/v0.4.3)
