### ISSUE TITLE
Problem connecting

### ISSUE THREAD

**Issue by MoltoMorto** [PimDoos/onesmartcontrolha#68]
Cant understand what the imputs need to connect
username: is the mail account connected with the account?
password: ...
host: the peripheral IP?
port: 9010... ore else?

**Comment by PimDoos** [comment]
Host is the IP address of your OneConnect box. Port is always 9010.
Username and password are the same ones you use to log in to the OneSmartControl mobile app.

**Comment by MoltoMorto** [comment]
> OneSmartControl mobile app

Maybe I'm too old... I've installed the 'OneSmart' app and not the 'OneSmart Control' as the Nexta required due to connect to the light and motors controls.
Sorry for the 'opened issue'.
Maybe I need to contact the Supplier.

**Comment by PimDoos** [comment]
Closing this issue as this integration is for One Smart Control, not Nexta OneSmart
